import FOLDER from "./CHALLENGE_1_FOLDER.jsx";
import PAGINATION from "./CHALLENGE_2_PAGINATION.jsx";
import CALCULATOR from "./CHALLENGE_3_EMICALCULATOR.jsx";
import PASSWORD from "./CHALLENGE_4_PASSWORD_GEN.jsx";
import PROGRESSBAR from "./CHALLENGE_5_PROGRESS_BAR.jsx";

export { FOLDER, PAGINATION, CALCULATOR, PASSWORD, PROGRESSBAR };
