import FOLDER from "./CHALLENGE_1_FOLDER.jsx";
import PAGINATION from "./CHALLENGE_2_PAGINATION.jsx";
import CALCULATOR from "./CHALLENGE_3_EMICALCULATOR.jsx";
import PASSWORD from "./CHALLENGE_4_PASSWORD_GEN.jsx";
import PROGRESSBAR from "./CHALLENGE_5_PROGRESS_BAR.jsx";
import GRIDLIGHT from "./CHALLENGE_6_GRIDLIGHTS.jsx";
import USEMEMO from "./CHALLENGE_7_USEMEMO.jsx";

export {
  FOLDER,
  PAGINATION,
  CALCULATOR,
  PASSWORD,
  PROGRESSBAR,
  GRIDLIGHT,
  USEMEMO,
};
