import FOLDER from "./CHALLENGE_1_FOLDER.jsx";
import PAGINATION from "./CHALLENGE_2_PAGINATION.jsx";
import CALCULATOR from "./CHALLENGE_3_EMICALCULATOR.jsx";

export { FOLDER, PAGINATION, CALCULATOR };
